### ISSUE TITLE
Question About SFT Data

### ISSUE THREAD

**Issue by chenhengzh** [yuyq18/StepTool#4]
I noticed that you chose to resample expert paths using GPT-4 instead of directly utilizing ToolBench data. I’m curious to know the reasoning behind this decision—were there specific concerns or objectives that prompted this approach?

Additionally, it seems that the performance of Llama3.1-SFT trained with your data does not significantly outperform ToolLlama, which uses a more powerful base model. Could this be related to the quality of your dataset not being higher than that of ToolBench?

Thank you for your time and for sharing your insights.

**Comment by yuyq18** [comment]
Thank you for your thoughtful questions! I’m happy to clarify the reasoning behind our decisions.

**1. Regarding the choice to resample expert paths using GPT-4 instead of directly utilizing ToolBench data:** 

ToolBench training data primarily uses **GPT-3.5 as the expert source**. Given that GPT-3.5 is now relatively outdated compared to GPT-4, we aimed to perform supervised fine-tuning (SFT) using more up-to-date and higher-quality data generated by GPT-4. Additionally, we believe that aligning the SFT data source with the RLHF phase—where GPT-4 annotations are used—creates a more consistent and natural pipeline. This approach allows us to attribute potential improvements to the RLHF method itself rather than substantial differences in data quality.

**2. Regarding the performance of Llama3.1-SFT trained with our data compared to ToolLlama:**

We believe the limited performance improvement primarily stems from the training scale. Due to time constraints, we opted to use a relatively small dataset (around 20k samples) and a limited number of training epochs (3 epochs), compared to ToolBench’s significantly larger dataset of 120k samples.

Furthermore, we do not believe that GPT-4-generated data presents lower quality than GPT-3.5-based ToolBench data. Thus, the suggestion that the performance gap arises from lower data quality may not be accurate.

**Clarification on our experimental focus:**

Our primary goal is to demonstrate that further step-level RLHF can effectively improve the model after a simple SFT stage. While improving performance during SFT by enhancing data quality or diversity is an active area of research[1][2], our work focuses specifically on leveraging RLHF techniques to achieve additional improvements beyond the SFT stage.

Thank you again for your questions and interest in our work. Please feel free to reach out if you have further inquiries!

> [1] Ibrahim Abdelaziz, Kinjal Basu, Mayank Agarwal, Sadhana Kumaravel, Matthew Stallone, Rameswar Panda, Yara Rizk, GP Bhargav, Maxwell Crouse, Chulaka Gunasekara, et al. Granite-function calling model: Introducing function calling abilities via multi-task learning of granular tasks. arXiv preprint arXiv:2407.00121, 2024.
> [2] Zuxin Liu, Thai Hoang, Jianguo Zhang, Ming Zhu, Tian Lan, Shirley Kokane, Juntao Tan, Weiran Yao, Zhiwei Liu, Yihao Feng, et al. Apigen: Automated pipeline for generating verifiable and diverse function-calling datasets. arXiv preprint arXiv:2406.18518, 2024.

**Comment by chenhengzh** [comment]
Thank you for your detailed response! I hadn’t noticed the training scale before. I believe that introducing reinforcement learning methods to tool learning is a significant contribution, and it’s the primary reason I appreciate this paper so much.
